apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: development
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'read-only-from-vault'
        vault.hashicorp.com/agent-inject-secret-dbcred: 'secret/dbcred'
         vault.hashicorp.com/agent-inject-template-dbcred: |
          {{- with secret "secret/dbcred" -}}
          export DB_NAME={{ .Data.data.db }}
          export DB_HOST={{ .Data.data.host }}
          export DB_USERNAME={{ .Data.data.username }}
          export DB_PASSWORD={{ .Data.data.password }}
          {{- end }}
      labels:
        app: my-app
    spec:
      serviceAccountName: vault-svc-account  # <-- This goes under spec.template.spec
      containers:
      - name: my-app
        image: nginx
