apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: development
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "read-only-from-vault"
    vault.hashicorp.com/agent-inject-secret-DB-VAULT-DEV: "secret/DB-VAULT-DEV"
    vault.hashicorp.com/agent-inject-template-db-credentials: |
      {{- with secret "secret/db-credentials" -}}
      export DB_HOST={{ .Data.data.host }}
      export DB_USERNAME={{ .Data.data.username }}
      export DB_PASSWORD={{ .Data.data.password }}
      {{- end }} 
  labels:
        app: my-app
spec:
  serviceAccountName: vault-svc-account
  containers:
  - name: my-app
    image: nginx
