apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: development
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "read-only-from-vault"
    vault.hashicorp.com/agent-inject-secret-myuberkey: "secret/myuberkey" 
  labels:
        app: my-app
spec:
  serviceAccountName: vault-svc-account
  containers:
  - name: my-app
    image: nginx
